# - id: https://doi.org/10.1101/2022.07.12.499846
#   title: "scDREAMER: atlas-level integration of single-cell datasets using deep generative model paired with adversarial classifier"
#   authors:
#   - Ajita Shree
#   - Musale Krushna Pavan
#   - Hamim Zafar
#   publisher: bioRxiv
#   date: ''
#   link: https://www.biorxiv.org/content/10.1101/2022.07.12.499846v1
#   image: 
#   repo: Zafar-Lab/scDREAMER
#   extra-links:

- id: doi:10.1101/2022.07.12.499846
  image: https://www.biorxiv.org/content/biorxiv/early/2022/07/14/2022.07.12.499846/F1.large.jpg?width=800&height=600&carousel=1
  date: 2022-07-14
  tags:
    - Data Integration, VAE, Adverserial learning.

- id: doi:10.1093/bioinformatics/btac254
  image: https://www.google.com/search?q=bioinformatics+journal&tbm=isch&ved=2ahUKEwj-v_eUjIP6AhUY7nMBHY47DvsQ2-cCegQIABAA&oq=Bioinformatics+jou&gs_lcp=CgNpbWcQARgAMgUIABCABDIECAAQGDIECAAQGDIECAAQGDIECAAQGDIECAAQGDIECAAQGDIECAAQGDIECAAQGDIECAAQGDoECCMQJzoKCAAQsQMQgwEQQzoECAAQQzoGCAAQHhAFUI8EWNYJYOoQaABwAHgAgAGVAYgBxgWSAQMwLjWYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=9cUYY77xIJjcz7sPjve42A8&bih=680&biw=1440#imgrc=A6YyJf9cMy_88M

- id: doi:10.1093/nar/gkac412
  image: https://academic.oup.com/view-large/figure/369644224/gkac412fig1.jpg
  repo: Zafar-Lab/Margaret

- id: doi:10.1101/2022.01.23.477444

- id: doi:10.1101/2021.01.12.426460

# - id: doi:10.1371/journal.pcbi.1007128
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   repo: greenelab/meta-review
#   extra-links:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#   extra-links:
#     - type: preprint
#       link: https://doi.org/10.7287/peerj.preprints.3100v1
#     - type: manubot
#       link: https://greenelab.github.io/scihub-manuscript/
#     - type: source
#       link: https://github.com/greenelab/scihub-manuscript
#       text: Manuscript source
#     - type: source
#       link: https://github.com/greenelab/scihub
#       text: Analyses source
